Repository project-error/npwd, pull requests merged in 2021-05, with the labels that each got.

#212 Keep input while phone is open
  fxmanifest.lua
  resources/client/cl_controls.lua
  resources/client/cl_main.ts
Labels: Draft (Work in Progress), Needs Revision

#232 feat(client/call): make pma-voice the default export
  resources/client/cl_call.ts
Labels: Awaiting Code Review

#231 Fix double call history & adding contact from history
  import.sql
  phone/src/apps/dialer/components/views/DialerHistory.tsx
  resources/client/cl_main.ts
  resources/server/calls/calls.service.ts
  resources/server/players/player.controller.ts
  resources/server/sv_main.ts
Labels: Awaiting Code Review

#241 Fix: Player ready stuff
  phone/src/Phone.tsx
  phone/src/os/phone/hooks/state.ts
  phone/src/os/phone/hooks/usePhone.ts
  phone/src/os/phone/hooks/usePhoneService.ts
  resources/client/cl_main.ts
  resources/server/players/player.controller.ts
  resources/server/players/player.service.ts
Labels: Awaiting Code Review, Awaiting Testing

#234 Disable walking when an inputfield is focused
  phone/src/apps/bank/components/transfers/TransferModal.tsx
  phone/src/apps/contacts/components/views/ContactInfo.tsx
  phone/src/apps/dialer/components/DialerInput.tsx
  phone/src/apps/marketplace/components/form/ListingForm.tsx
  phone/src/apps/messages/components/form/MessageInput.tsx
  phone/src/apps/messages/components/form/NewMessageGroupForm.tsx
  phone/src/apps/notes/modal/NoteModal.tsx
  phone/src/apps/settings/components/WallpaperModal.tsx
  phone/src/apps/twitter/components/TwitterSearch.tsx
  phone/src/apps/twitter/components/images/ImagePrompt.tsx
  phone/src/apps/twitter/components/tweet/TweetMessage.tsx
  phone/src/ui/components/Input.tsx
  phone/src/ui/components/ProfileField.tsx
  phone/src/ui/components/SearchField.tsx
  resources/client/cl_main.ts
  typings/phone.ts
Labels: Awaiting Code Review, Awaiting Testing
