Repository project-error/npwd, pull requests merged in 2021-02, with the labels that each got.

#67 Fix warnings + Improve CallTimer
  phone/src/apps/camera/components/grid/GalleryGrid.tsx
  phone/src/apps/contacts/hooks/useContacts.ts
  phone/src/apps/dialer/components/DialerNavBar.tsx
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/list/MessagesList.tsx
  phone/src/modal/components/CallModal.tsx
  phone/src/modal/components/CallTimer.tsx
  phone/src/modal/hooks/useCall.ts
  phone/src/os/apps/hooks/useApps.tsx
  phone/src/os/nui-events/hooks/useNuiEvent.ts
  phone/src/ui/components/AppIcon.tsx
  resources/client/cl_photo.ts
  resources/server/sv_call.ts
  resources/server/sv_photo.ts
  resources/utils/events.ts
Labels: enhancement

#72 Improved install instructions and cleanup.
  README.md
Labels: Documentation

#77 Fix: Dialer Routing, added contacts and styling.
  phone/src/apps/contacts/components/ContactsApp.tsx
  phone/src/apps/contacts/components/List/ContactList.tsx
  phone/src/apps/contacts/components/List/SearchContacts.tsx
  phone/src/apps/dialer/components/DialPadGrid.tsx
  phone/src/apps/dialer/components/DialerApp.tsx
  phone/src/apps/dialer/components/DialerNavBar.tsx
  phone/src/apps/dialer/components/views/DialPage.tsx
  phone/src/config/default.json
Labels: Tracked Issue

#64 fix twitter for light theme
  phone/src/apps/twitter/components/AddTweetModal.tsx
  phone/src/apps/twitter/components/tweet/Tweet.tsx
  phone/src/apps/twitter/components/tweet/TweetMessage.tsx
  phone/src/ui/components/Modal.tsx
Labels: Tracked Issue

#79 Fix/notes handling
  phone/src/apps/notes/NotesApp.tsx
  phone/src/apps/notes/alert/NotesAlert.tsx
  phone/src/apps/notes/hooks/state.ts
  phone/src/apps/notes/hooks/useNoteAlert.ts
  phone/src/apps/notes/hooks/useNotesService.ts
  phone/src/apps/notes/modal/NoteModal.tsx
  phone/src/common/typings/notes.ts
  phone/src/locale/en.json
  resources/client/cl_notes.ts
  resources/server/sv_notes.ts
  resources/utils/apps.ts
  resources/utils/events.ts
  resources/utils/messages.ts
Labels: Enhancement

#85 Translation: Update fr.json
  phone/src/locale/fr.json
Labels: Translation

#100 Fix: Call history is now sorted.
  resources/server/sv_call.ts
Labels: Tracked Pull Request

#99 Fix SQL import file collation
  resources/import.sql
Labels: Tracked Pull Request

#101 Feature / Autocomplete contacts in messages + improve messages ui a bit
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/buttons/NewMessageGroupButton.tsx
  phone/src/apps/messages/components/form/MessageInput.tsx
  phone/src/apps/messages/components/form/NewMessageGroupForm.tsx
  phone/src/apps/messages/components/form/form.styles.ts
  phone/src/apps/messages/components/modal/Conversation.tsx
  phone/src/apps/messages/components/modal/modal.styles.ts
  phone/src/locale/en.json
  phone/src/locale/fr.json
  phone/yarn.lock
  resources/client/cl_main.ts
Labels: Tracked Pull Request
