Repository project-error/npwd, pull requests merged in 2021-12, with the labels that each got.

#338 Refactor/twitter
  phone/src/apps/match/components/profile/ProfileForm.tsx
  phone/src/apps/twitter/components/AddTweetModal.tsx
  phone/src/apps/twitter/components/EmojiSelect.tsx
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/components/TwitterContainer.tsx
  phone/src/apps/twitter/components/TwitterSearch.tsx
  phone/src/apps/twitter/components/buttons/LikeButton.tsx
  phone/src/apps/twitter/components/buttons/ReportButton.tsx
  phone/src/apps/twitter/components/buttons/RetweetButton.tsx
  phone/src/apps/twitter/components/buttons/SearchButton.tsx
  phone/src/apps/twitter/components/profile/DefaultProfilePrompt.tsx
  phone/src/apps/twitter/components/profile/Profile.tsx
  phone/src/apps/twitter/components/profile/ProfilePrompt.tsx
  phone/src/apps/twitter/components/tweet/ShowMore.tsx
  phone/src/apps/twitter/components/tweet/Tweet.tsx
  phone/src/apps/twitter/components/tweet/TweetList.tsx
  phone/src/apps/twitter/components/tweet/TweetListContainer.tsx
  phone/src/apps/twitter/components/tweet/TweetMessage.tsx
  phone/src/apps/twitter/hooks/state.ts
  phone/src/apps/twitter/hooks/useTwitterActions.ts
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  phone/src/apps/twitter/utils/tweets.ts
  phone/src/locale/en.json
  phone/src/os/apps/config/apps.tsx
  resources/client/cl_main.ts
  resources/client/cl_twitter.ts
  resources/server/players/player.utils.ts
  resources/server/twitter/twitter.controller.ts
  resources/server/twitter/twitter.db.ts
  resources/server/twitter/twitter.service.ts
Labels: Enhancement, Awaiting Testing

#374 fix: emit CALL_ENDED and CALL_REJECTED events to both source and target
  resources/server/calls/calls.service.ts
Labels: Awaiting Code Review

#414 Final Czech Language
  phone/src/config/default.json
  phone/src/i18n.ts
  phone/src/locale/cs.json
Labels: To be merged

#415 Dutch Locales
  phone/src/config/default.json
  phone/src/i18n.ts
  phone/src/locale/nl.json
Labels: Translation

#424 tweak(locales/cs): Text correction
  phone/src/locale/cs.json
Labels: To be merged

#423 New french translation to fit with new format
  phone/src/locale/fr.json
Labels: To be merged

#440 Update no.json
  phone/src/locale/no.json
Labels: Translation, To be merged

#444 Gh 348/repopulate conversations
  phone/src/apps/messages/hooks/useMessageNotifications.ts
  phone/src/locale/en.json
  resources/server/messages/messages.service.ts
Labels: Awaiting Code Review, Awaiting Testing, Priority

#439 feat(locale/cs): Add missing translations
  phone/src/locale/cs.json
Labels: To be merged

#452 Kidz/432 dialer history not showing display name
  phone/src/apps/dialer/components/views/DialerHistory.tsx
  phone/src/apps/dialer/hooks/state.ts
Labels: Awaiting Code Review, Awaiting Testing
