Repository project-error/npwd, pull requests merged in 2021-03, with the labels that each got.

#118 feat/messages additions (in memory of Leonard Nimoy )
  .husky/_/husky.sh
  .husky/pre-commit
  phone/src/Phone.css
  phone/src/Phone.tsx
  phone/src/apps/contacts/components/ContactsApp.tsx
  phone/src/apps/contacts/components/views/ContactInfo.tsx
  phone/src/apps/contacts/hooks/useContacts.ts
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/form/MessageInput.tsx
  phone/src/apps/messages/components/list/MessageGroupItem.tsx
  phone/src/apps/messages/components/list/MessagesList.tsx
  phone/src/apps/messages/components/modal/Conversation.tsx
  phone/src/apps/messages/components/modal/MessageBubble.tsx
  phone/src/apps/messages/components/modal/MessageModal.tsx
  phone/src/apps/messages/components/modal/modal.styles.ts
  phone/src/apps/messages/hooks/state.ts
  phone/src/apps/messages/hooks/useMessageNotifications.ts
  phone/src/apps/messages/hooks/useMessageService.ts
  phone/src/apps/messages/hooks/useMessages.ts
  phone/src/apps/messages/utils/goToConversation.ts
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/common/typings/messages.ts
  phone/src/locale/en.json
  phone/src/os/call/hooks/useCallNotifications.tsx
  phone/src/os/call/hooks/useCallService.tsx
  phone/src/os/notifications/providers/NotificationsProvider.tsx
  phone/src/os/phone/hooks/useClipboard.ts
  phone/src/os/phone/hooks/usePhoneVisibility.ts
  phone/src/ui/components/ContextMenu.tsx
  phone/src/ui/components/Modal.tsx
  phone/src/ui/hooks/useContextMenu.tsx
  resources/client/cl_messages.ts
  resources/import.sql
  resources/server/functions.ts
  resources/server/sv_call.ts
  resources/server/sv_logger.ts
  resources/server/sv_messages.ts
  resources/utils/events.ts
Labels: Needs Revision

#135 tweak(phone/snackbar-provider): Altered API
  phone/src/apps/bank/hooks/useBankService.ts
  phone/src/apps/calculator/components/Calculator.tsx
  phone/src/apps/contacts/hooks/useContactsService.ts
  phone/src/apps/messages/hooks/useMessageService.ts
  phone/src/apps/notes/hooks/useNotesService.ts
  phone/src/apps/sellout/hooks/useSelloutService.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  phone/src/locale/en.json
  phone/src/ui/components/Snackbar.tsx
  phone/src/ui/hooks/useSnackbar.ts
Labels: Awaiting Review, Awaiting Testing

#144 Bugfix / Fix message bubble, notifications slideup phone and overflow and conversation scrolling
  phone/src/Phone.tsx
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/modal/Conversation.tsx
  phone/src/apps/messages/components/modal/MessageBubble.tsx
  phone/src/apps/messages/components/modal/MessageModal.tsx
  phone/src/apps/messages/components/modal/modal.styles.ts
  phone/src/os/phone/hooks/usePhoneVisibility.ts
Labels: Awaiting Code Review

#140 Tweak / Improve transition to MessageModal (conversation)
  phone/src/apps/messages/components/modal/MessageModal.tsx
  phone/src/apps/messages/hooks/useMessageService.ts
Labels: Awaiting Code Review

#145 feat(client/debug): Phone restart command
  phone/src/Phone.tsx
  phone/src/ui/components/WindowSnackbar.tsx
  resources/client/cl_main.ts
Labels: Awaiting Code Review

#146 fix(phone/snackbar): Fixed animations & simplified logic
  phone/src/Phone.tsx
  phone/src/ui/components/Alert.tsx
  phone/src/ui/components/PhoneSnackbar.tsx
  phone/src/ui/hooks/useSnackbar.ts
  phone/src/ui/providers/SnackbarProvider.tsx
Labels: Awaiting Code Review

#143 [Feature] Twitter retweets
  import.sql
  phone/src/apps/twitter/components/AddTweetModal.tsx
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/components/buttons/QuoteButton.tsx
  phone/src/apps/twitter/components/buttons/RetweetButton.tsx
  phone/src/apps/twitter/components/tweet/Retweet.tsx
  phone/src/apps/twitter/components/tweet/Tweet.tsx
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  phone/src/apps/twitter/providers/TwitterThemeProvider.tsx
  phone/src/apps/twitter/twitter.theme.ts
  phone/src/common/typings/twitter.ts
  phone/src/locale/en.json
  resources/client/cl_twitter.ts
  resources/server/sv_twitter.ts
  resources/utils/events.ts
Labels: Awaiting Code Review

#147 Feature/Twitter Notification Filters
  phone/src/Phone.tsx
  phone/src/apps/settings/components/SettingsApp.tsx
  phone/src/apps/settings/hooks/useSettings.ts
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/components/profile/Profile.tsx
  phone/src/apps/twitter/hooks/state.ts
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  phone/src/apps/twitter/utils/constants.ts
  phone/src/common/typings/twitter.ts
  phone/src/config/default.json
  phone/src/locale/en.json
  phone/src/ui/hooks/useContextMenu.tsx
  resources/server/sv_main.ts
  resources/server/sv_twitter.ts
Labels: Awaiting Code Review

#137 Tweak/marketplace additions
  import.sql
  phone/src/apps/sellout/components/SelloutApp.tsx
  phone/src/apps/sellout/components/SelloutList/ListingActions.tsx
  phone/src/apps/sellout/components/SelloutList/SelloutItem.tsx
  phone/src/apps/sellout/components/SelloutList/SelloutList.tsx
  phone/src/apps/sellout/components/SelloutList/SelloutListContainer.tsx
  phone/src/apps/sellout/hooks/useListing.ts
  phone/src/common/typings/marketplace.ts
  phone/src/locale/en.json
  resources/client/cl_sellout.ts
  resources/server/discord.ts
  resources/server/sv_sellout.ts
  resources/utils/events.ts
Labels: Needs Revision

#158 refactor(server/discord): Refactored Discord reports to use webhooks
  resources/server/discord.ts
Labels: Awaiting Code Review, Awaiting Testing

#155 feat(resources): remove all esx code, almost
  resources/client/cl_main.ts
  resources/server/functions.ts
  resources/server/players/sv_player_events.ts
  resources/server/players/sv_players.ts
  resources/server/server.ts
  resources/server/sv_bank.ts
  resources/server/sv_call.ts
  resources/server/sv_contacts.ts
  resources/server/sv_main.ts
  resources/server/sv_messages.ts
  resources/server/sv_notes.ts
  resources/server/sv_sellout.ts
  resources/server/sv_twitter.ts
  resources/typings/players.ts
  resources/utils/events.ts
Labels: Priority

#161 Fix remaining issues for messages
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/modal/MessageModal.tsx
Labels: Draft (Work in Progress)

#159 Feature / Streamer Mode
  phone/src/Phone.tsx
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/modal/MessageBubble.tsx
  phone/src/apps/sellout/components/SelloutList/SelloutItem.tsx
  phone/src/apps/settings/components/SettingItem.tsx
  phone/src/apps/settings/components/SettingsApp.tsx
  phone/src/apps/settings/hooks/useSettings.ts
  phone/src/apps/twitter/components/EmojiSelect.tsx
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/components/buttons/ControlButtons.tsx
  phone/src/apps/twitter/components/buttons/LikeButton.tsx
  phone/src/apps/twitter/components/buttons/RetweetButton.tsx
  phone/src/apps/twitter/components/buttons/SearchButton.tsx
  phone/src/apps/twitter/components/images/Image.tsx
  phone/src/apps/twitter/components/images/ImageDisplay.tsx
  phone/src/apps/twitter/components/profile/Profile.tsx
  phone/src/apps/twitter/components/tweet/Retweet.tsx
  phone/src/apps/twitter/components/tweet/Tweet.tsx
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  phone/src/apps/twitter/twitter.theme.ts
  phone/src/config/default.json
  phone/src/locale/en.json
  phone/src/os/apps/config/apps.tsx
  phone/src/os/call/components/CallModal.tsx
  phone/src/os/sound/utils/getSoundSettings.ts
  phone/src/ui/components/PictureReveal.tsx
Labels: Awaiting Code Review

#166 replaced all imgur images to iodine images :)
  README.md
  import.sql
  phone/src/apps/camera/components/CameraApp.tsx
  phone/src/apps/sellout/components/SelloutApp.tsx
  phone/src/os/debug/InjectDebugData.ts
Labels: Awaiting Code Review, Awaiting Testing

#164 Messages bugfix again :D
  phone/src/Phone.tsx
  phone/src/apps/example/components/ExampleApp.tsx
  phone/src/apps/messages/components/form/NewMessageGroupForm.tsx
  phone/src/apps/messages/components/list/MessageGroupItem.tsx
  phone/src/apps/messages/components/list/MessagesList.tsx
  phone/src/apps/messages/components/modal/MessageModal.tsx
  phone/src/apps/messages/hooks/useMessageNotifications.ts
  phone/src/apps/messages/hooks/useMessageService.ts
  phone/src/apps/messages/utils/goToConversation.ts
  phone/src/apps/settings/utils/getRingtonePath.ts
  phone/src/apps/twitter/utils/constants.ts
  resources/server/sv_messages.ts
Labels: Priority

#160 Feature/twitter refresh
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  typings/twitter.ts
Labels: Awaiting Code Review, Needs Revision

#170 Feature/default profile names
  phone/src/apps/messages/components/modal/MessageModal.tsx
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/components/profile/DefaultProfilePrompt.tsx
  phone/src/apps/twitter/components/profile/ProfilePrompt.tsx
  phone/src/apps/twitter/hooks/state.ts
  phone/src/apps/twitter/hooks/useTwitterNotifications.ts
  phone/src/apps/twitter/hooks/useTwitterService.ts
  phone/src/locale/en.json
  resources/client/cl_main.ts
  resources/client/cl_twitter.ts
  resources/server/players/sv_players.ts
  resources/server/sv_main.ts
  resources/server/sv_twitter.ts
  resources/utils/events.ts
Labels: PR Conflicts

#179 Feature/tinder
  config.json
  import.sql
  phone/src/Phone.tsx
  phone/src/apps/match/components/ActiveProfile.tsx
  phone/src/apps/match/components/BottomNavigation.tsx
  phone/src/apps/match/components/Draggable.tsx
  phone/src/apps/match/components/Error.tsx
  phone/src/apps/match/components/Loader.tsx
  phone/src/apps/match/components/MatchApp.tsx
  phone/src/apps/match/components/PageText.tsx
  phone/src/apps/match/components/StatusDisplay.tsx
  phone/src/apps/match/components/matches/Match.tsx
  phone/src/apps/match/components/profile/Profile.tsx
  phone/src/apps/match/components/profile/ProfileForm.tsx
  phone/src/apps/match/components/views/MatchList.tsx
  phone/src/apps/match/components/views/MatchPage.tsx
  phone/src/apps/match/components/views/ProfileEditor.tsx
  phone/src/apps/match/hooks/state.ts
  phone/src/apps/match/hooks/useMatchService.ts
  phone/src/apps/match/hooks/useMatches.ts
  phone/src/apps/match/hooks/useProfile.ts
  phone/src/apps/match/hooks/useProfiles.ts
  phone/src/apps/match/match.theme.ts
  phone/src/apps/match/providers/MatchThemeProvider.tsx
  phone/src/apps/match/utils/drag.ts
  phone/src/apps/twitter/components/buttons/ProfileUpdateButton.tsx
  phone/src/apps/twitter/components/profile/Profile.tsx
  phone/src/apps/twitter/components/profile/ProfilePrompt.tsx
  phone/src/config.autogen.json
  phone/src/locale/en.json
  phone/src/os/apps/config/apps.tsx
  phone/src/os/notifications/components/NotificationItem.tsx
  phone/src/ui/components/ProfileField.tsx
  phone/src/ui/components/UpdateButton.tsx
  phone/yarn.lock
  resources/client/cl_main.ts
  resources/client/cl_match.ts
  resources/client/client.ts
  resources/server/players/sv_players.ts
  resources/server/server.ts
  resources/server/sv_match.ts
  resources/server/sv_twitter.ts
  resources/utils/apps.ts
  resources/utils/messages.ts
  typings/config.ts
  typings/match.ts
Labels: Awaiting Code Review, Awaiting Testing

#184 Improve/marketplace
  phone/src/Phone.tsx
  phone/src/apps/marketplace/components/MarketplaceApp.tsx
  phone/src/apps/marketplace/components/MarketplaceTitle.tsx
  phone/src/apps/marketplace/components/SelloutList/ListingActions.tsx
  phone/src/apps/marketplace/components/SelloutList/MarketplaceItem.tsx
  phone/src/apps/marketplace/components/SelloutList/MarketplaceList.tsx
  phone/src/apps/marketplace/components/SelloutList/MarketplaceListContainer.tsx
  phone/src/apps/marketplace/components/form/ListingForm.tsx
  phone/src/apps/marketplace/components/form/ListingFormContainer.tsx
  phone/src/apps/marketplace/components/navigation/NavigationBar.tsx
  phone/src/apps/marketplace/hooks/state.ts
  phone/src/apps/marketplace/hooks/useListing.ts
  phone/src/apps/marketplace/hooks/useMarketplaceService.ts
  phone/src/apps/marketplace/marketplace.theme.ts
  phone/src/apps/marketplace/providers/MarketplaceThemeProvider.tsx
  phone/src/apps/sellout/components/SelloutList/SelloutListContainer.tsx
  phone/src/apps/sellout/providers/SelloutThemeProvider.tsx
  phone/src/locale/en.json
  phone/src/os/apps/config/apps.tsx
  resources/client/cl_marketplace.ts
  resources/client/client.ts
  resources/server/server.ts
  resources/server/sv_marketplace.ts
Labels: Awaiting Code Review, Awaiting Testing, PR Conflicts
