Repository project-error/npwd, pull requests merged in 2021-04, with the labels that each got.

#195 Bugfix / Remove paste from clipboard feature in messages app
  phone/src/apps/messages/components/modal/MessageImageModal.tsx
Labels: Awaiting Code Review

#178 tweak(phone/call-modal): Tweaked appearance of call modal
  phone/src/apps/contacts/components/ContactsApp.tsx
  phone/src/apps/contacts/hooks/useContacts.ts
  phone/src/apps/settings/utils/getBackgroundPath.ts
  phone/src/locale/en.json
  phone/src/os/call/components/CallContactContainer.tsx
  phone/src/os/call/components/CallControls.tsx
  phone/src/os/call/components/CallModal.tsx
  phone/src/os/call/components/CallNotification.tsx
  phone/src/os/call/components/CallTimer.tsx
  phone/src/os/call/components/RingingText.tsx
  phone/src/os/call/hooks/useCallService.tsx
  phone/src/os/call/hooks/useDuration.ts
  phone/src/os/call/hooks/useTimer.ts
  phone/src/ui/components/AppContent.tsx
  phone/src/ui/interface/InterfaceUI.ts
Labels: Awaiting Code Review

#185 tweak(phone/settings): simplify custom background
  phone/src/Phone.tsx
  phone/src/apps/settings/components/SettingItem.tsx
  phone/src/apps/settings/components/SettingsApp.tsx
  phone/src/apps/settings/components/WallpaperModal.tsx
  phone/src/apps/settings/hooks/useSettings.ts
  phone/src/apps/settings/utils/isDefaultWallpaper.ts
  phone/src/locale/en.json
  phone/src/locale/no.json
  phone/src/ui/components/DialogForm.tsx
Labels: Needs Revision, Stale

#202 Fix fetch on initialize (fixing notifications too)
  phone/src/apps/messages/components/form/MessageInput.tsx
  phone/src/os/phone/hooks/usePhoneService.ts
  resources/client/cl_main.ts
  typings/phone.ts
Labels: Awaiting Code Review, Awaiting Testing

#200 Feature / Add loading state to camera app
  phone/src/apps/camera/components/grid/GalleryGrid.tsx
  phone/src/apps/camera/components/modal/GalleryModal.tsx
  phone/src/apps/camera/components/modal/ShareModal.tsx
  phone/src/apps/camera/hooks/state.ts
  phone/src/apps/camera/hooks/useCamera.ts
  phone/src/apps/camera/hooks/usePhotos.ts
  phone/src/locale/en.json
  resources/client/cl_photo.ts
  resources/server/sv_photo.ts
  typings/photo.ts
Labels: Awaiting Code Review

#189 Recoil State Type Safety + Misc Cleanup
  phone/src/Phone.tsx
  phone/src/apps/camera/components/modal/GalleryModal.tsx
  phone/src/apps/camera/components/modal/ShareModal.tsx
  phone/src/apps/camera/hooks/state.ts
  phone/src/apps/camera/hooks/useCamera.ts
  phone/src/apps/contacts/hooks/state.ts
  phone/src/apps/contacts/hooks/useFilteredContacts.ts
  phone/src/apps/dialer/components/views/DialerHistory.tsx
  phone/src/apps/dialer/hooks/state.ts
  phone/src/apps/dialer/hooks/useDialHistory.ts
  phone/src/apps/marketplace/hooks/state.ts
  phone/src/apps/match/components/BottomNavigation.tsx
  phone/src/apps/match/hooks/state.ts
  phone/src/apps/messages/hooks/state.ts
  phone/src/apps/messages/hooks/useMessages.ts
  phone/src/apps/settings/hooks/useSettings.ts
  phone/src/os/call/components/CallNotification.tsx
  phone/src/os/call/hooks/state.ts
  phone/src/os/call/hooks/useCall.ts
  phone/src/os/call/hooks/useCallNotifications.tsx
  phone/src/os/call/hooks/useCallService.tsx
  phone/src/os/phone/hooks/settingState.ts
  phone/src/os/phone/hooks/state.ts
  phone/src/os/phone/hooks/usePhoneService.ts
  phone/src/os/simcard/hooks/useSimcardService.ts
  phone/src/ui/components/Notification.tsx
  resources/client/cl_call.ts
  resources/client/cl_main.ts
  resources/client/cl_photo.ts
  resources/server/sv_call.ts
  resources/server/sv_main.ts
  resources/server/sv_photo.ts
  typings/call.ts
  typings/phone.ts
  typings/photo.ts
Labels: Awaiting Code Review, Awaiting Testing
