Repository project-error/npwd, pull requests merged in 2022-01, with the labels that each got.

#442 feat(locale/es): update to new translations
  phone/src/locale/es.json
Labels: Translation, To be merged

#471 chore(locale/hu): Update hungarian locale file
  phone/src/locale/hu.json
Labels: Translation, To be merged

#470 feat(locale/it): Added Italian lang file
  phone/src/config/default.json
  phone/src/i18n.ts
  phone/src/locale/it.json
Labels: Translation, To be merged

#473 feat(locale/pl): Add Polish language translations
  phone/src/config/default.json
  phone/src/i18n.ts
  phone/src/locale/pl.json
Labels: Translation, Change Requested

#482 feat(locale/id): added indonesia language
  phone/src/config/default.json
  phone/src/i18n.ts
  phone/src/locale/id.json
Labels: Translation, To be merged

#486 locale(ba): updated bosnian locale
  phone/src/config/default.json
  phone/src/locale/ba.json
Labels: Translation, To be merged

#495 refactor(messages): remove modal & replace with icons
  phone/src/apps/messages/components/modal/MessageModal.tsx
Labels: To be merged

#504 Additonal lines to Hungarian translate from new Eng.
  phone/src/locale/hu.json
Labels: To be merged

#484 feat(phone/settings): call volume slider in settings
  phone/src/Phone.tsx
  phone/src/apps/settings/components/SettingsApp.tsx
  phone/src/apps/settings/components/SettingsCategory.tsx
  phone/src/apps/settings/components/WallpaperModal.tsx
  phone/src/apps/settings/hooks/useSettings.ts
  phone/src/apps/settings/state/customWallpaper.state.ts
  phone/src/apps/settings/state/settings.state.ts
  phone/src/config/default.json
  phone/src/locale/de.json
  phone/src/locale/en.json
  phone/src/locale/es.json
  phone/src/locale/fi.json
  phone/src/locale/fr.json
  phone/src/locale/hu.json
  phone/src/locale/it.json
  phone/src/locale/nl.json
  phone/src/locale/no.json
  phone/src/locale/pt.json
  phone/src/os/apps/hooks/useApps.tsx
  phone/src/os/sound/utils/getSoundSettings.ts
  resources/client/settings/cl_settings.ts
  typings/settings.ts
Labels: Enhancement, Frontend

#458 [Calling] Feat: Dialing Tone during Outgoing Request Phase
  phone/src/os/call/hooks/state.ts
  phone/src/os/call/hooks/useCall.ts
  phone/src/os/call/hooks/useCallService.tsx
  phone/src/os/debug/AttachWindowDebug.ts
  phone/src/os/navigation-bar/components/Navigation.tsx
  phone/src/os/navigation-bar/state/navigation.state.ts
  phone/src/os/sound/hooks/useRingtoneSound.ts
  phone/tsconfig.json
  resources/client/calls/cl_calls.service.ts
  typings/call.ts
Labels: Awaiting Code Review, Awaiting Testing

#510 Updated Finnish translation
  phone/src/locale/fi.json
Labels: To be merged

#516 fix(phone/notification-bar): center time text
  phone/src/os/notifications/components/NotificationBar.tsx
Labels: Awaiting Code Review, Awaiting Testing, Priority

#520 Disable light melee attack
  resources/client/cl_controls.lua
Labels: To be merged

#518 fix(twitter): fix rerendering twitter app on every letter type
  phone/src/apps/twitter/components/AddTweetModal.tsx
  phone/src/apps/twitter/components/ModalBackground.tsx
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/apps/twitter/components/TwitterContainer.tsx
Labels: To be merged, Frontend

#477 feat: basic image filtering
  config.json
  phone/src/apps/camera/components/grid/GalleryGrid.tsx
  phone/src/apps/contacts/hooks/useContactsAPI.ts
  phone/src/apps/marketplace/components/form/ListingForm.tsx
  phone/src/apps/match/components/profile/ProfileForm.tsx
  phone/src/apps/twitter/components/profile/Profile.tsx
  phone/src/locale/en.json
  resources/client/cl_photo.ts
  resources/server/contacts/contacts.service.ts
  resources/server/marketplace/marketplace.controller.ts
  resources/server/marketplace/marketplace.service.ts
  resources/server/match/match.service.ts
  resources/server/messages/messages.service.ts
  resources/server/messages/messages.service.ts.rej
  resources/server/notes/notes.service.ts
  resources/server/photo/photo.service.ts
  resources/server/twitter/twitter.service.ts
  resources/server/utils/imageFiltering.ts
  typings/config.ts
  typings/contact.ts
  typings/marketplace.ts
  typings/match.ts
  typings/photo.ts
Labels: Awaiting Code Review, Awaiting Testing

#541 Update de.json
  phone/src/locale/de.json
Labels: To be merged

#551 test(phone/settings): add unit tests for setting state
  phone/package.json
  phone/src/Phone.test.tsx
  phone/src/Phone.tsx
  phone/src/apps/settings/hooks/useInvalidSettingsHandler.ts
  phone/src/apps/settings/state/settings.state.ts
  phone/src/apps/settings/state/settingsState.test.tsx
  phone/src/apps/settings/utils/constants.ts
  phone/src/apps/settings/utils/schema.ts
  phone/src/setupTests.ts
  phone/yarn.lock
Labels: Frontend

#559 feat(server/build-detector): inform user of missed build step
  build-detector.js
  fxmanifest.lua
Labels: Enhancement, Backend

#553 fix(call): fix being able to accept calls if player has no phone
  resources/client/calls/cl_calls.service.ts
  resources/client/cl_main.ts
Labels: Frontend

#567 Update and fix for spanish locale
  phone/src/locale/es.json
Labels: Translation, To be merged
