Repository project-error/npwd, pull requests merged in 2022-03, with the labels that each got.

#656 Update hu.json
  phone/src/locale/hu.json
Labels: Translation

#651 feat(config): added default config
  config.default.json
  config.json
  phone/craco.config.js
  phone/package.json
  phone/src/Phone.test.tsx
  phone/src/apps/settings/state/settings.state.ts
  phone/src/apps/settings/state/settingsState.test.tsx
  phone/src/os/apps/utils/createAppThemeProvider.tsx
  phone/src/os/phone/hooks/useConfig.ts
  phone/src/utils/__tests__/config.test.ts
  phone/src/utils/config.ts
  phone/src/utils/language.ts
  phone/tsconfig.paths.json
  resources/client/cl_config.ts
  resources/server/calls/calls.service.ts
  resources/server/config.ts
  resources/server/players/player.utils.ts
  resources/server/tsconfig.json
  resources/server/utils/config.ts
  resources/webpack.config.js
  shared/deepMergeObjects.ts
  typings/config.ts
Labels: Enhancement

#620 feat(server/debug): introduce 'npwd-debug-dump' command
  resources/server/commands/registerCommands.ts
  resources/server/db/parseUri.ts
  resources/server/server.ts
  resources/server/sv_logger.ts
Labels: To be merged, Backend
