Repository project-error/npwd, pull requests merged in 2022-02, with the labels that each got.

#593 Russian translation
  phone/i18n.missingKeys.js
  phone/src/config/default.json
  phone/src/i18n.ts
  phone/src/locale/ru.json
Labels: To be merged

#612 Fix locales
  phone/src/config/default.json
  phone/src/locale/newtr.json
  phone/src/locale/tr.json
Labels: Translation, Frontend

#613 chore(license): move towards the GPLv3 OSS license
  LICENSE
Labels: Discussion

#602 Debug stuff
  resources/client/cl_main.ts
  resources/server/boot/boot.controller.ts
  resources/server/boot/boot.db.ts
  resources/server/boot/boot.service.ts
  resources/server/boot/boot.utils.ts
  resources/server/server.ts
Labels: To be merged, Backend

#625 Feat/word filter
  config.json
  phone/src/apps/marketplace/components/MarketplaceApp.tsx
  phone/src/apps/marketplace/components/form/ListingForm.tsx
  phone/src/apps/messages/components/MessagesApp.tsx
  phone/src/apps/messages/components/form/MessageInput.tsx
  phone/src/apps/twitter/components/AddTweetModal.tsx
  phone/src/apps/twitter/components/TwitterApp.tsx
  phone/src/os/wordfilter/hooks/useWordFilter.ts
  phone/src/os/wordfilter/providers/WordFilterProvider.tsx
  typings/config.ts
Labels: Enhancement

#630 feat(app/calculator): decrease font-size based on result length
  phone/src/apps/calculator/components/Calculator.tsx
Labels: Awaiting Code Review

#629 feat(settings/language): added possibility to set default language
  config.json
  phone/src/Phone.tsx
  phone/src/apps/settings/state/settings.state.ts
  phone/src/os/phone/hooks/usePhone.ts
  phone/src/ui/components/GridMenu.tsx
  phone/src/utils/language.ts
Labels: To be merged
